<a href="https://colab.research.google.com/github/nirjana/Binary-classifier/blob/master/Binary_classifier_example_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install sklearn

Requirement already satisfied: sklearn in /usr/local/lib/python3.7/dist-packages (0.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from sklearn) (0.22.2.post1)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (1.4.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (1.0.1)
Requirement already satisfied: numpy>=1.11.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (1.19.5)

In [4]:
import numpy as np
import pandas as pd

import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [10]:
import pathlib

dataset_url = 'http://storage.googleapis.com/download.tensorflow.org/data/petfinder-mini.zip'
csv_file = 'datasets/petfinder-mini/petfinder-mini.csv'

tf.keras.utils.get_file('petfinder_mini.zip', dataset_url,
                        extract=True, cache_dir='.')
dataframe = pd.read_csv(csv_file)

In [6]:
dataframe.head()

  Type  Age  ... PhotoAmt AdoptionSpeed
0  Cat    3  ...        1             2
1  Cat    1  ...        2             0
2  Dog    1  ...        7             3
3  Dog    4  ...        8             2
4  Dog    1  ...        3             2

[5 rows x 15 columns]

In [11]:
gender = pd.get_dummies(dataframe.Gender)

In [8]:
merged = pd.concat([dataframe,gender],axis='columns')




merged

      Type  Age                Breed1  ... AdoptionSpeed Female Male
0      Cat    3                 Tabby  ...             2      0    1
1      Cat    1  Domestic Medium Hair  ...             0      0    1
2      Dog    1           Mixed Breed  ...             3      0    1
3      Dog    4           Mixed Breed  ...             2      1    0
4      Dog    1           Mixed Breed  ...             2      0    1
...    ...  ...                   ...  ...           ...    ...  ...
11532  Dog   24                Poodle  ...             4      0    1
11533  Cat    1   Domestic Short Hair  ...             3      1    0
11534  Dog    6             Schnauzer  ...             0      1    0
11535  Cat    9   Domestic Short Hair  ...             4      1    0
11536  Dog    1           Mixed Breed  ...             3      0    1

[11537 rows x 17 columns]

In [9]:
final = merged.drop(['Gender','Male'],axis='columns')
result = final.rename(columns={"Female": "Gender"})
result

      Type  Age                Breed1  ... PhotoAmt AdoptionSpeed Gender
0      Cat    3                 Tabby  ...        1             2      0
1      Cat    1  Domestic Medium Hair  ...        2             0      0
2      Dog    1           Mixed Breed  ...        7             3      0
3      Dog    4           Mixed Breed  ...        8             2      1
4      Dog    1           Mixed Breed  ...        3             2      0
...    ...  ...                   ...  ...      ...           ...    ...
11532  Dog   24                Poodle  ...        0             4      0
11533  Cat    1   Domestic Short Hair  ...        1             3      1
11534  Dog    6             Schnauzer  ...        1             0      1
11535  Cat    9   Domestic Short Hair  ...        3             4      1
11536  Dog    1           Mixed Breed  ...        1             3      0

[11537 rows x 15 columns]